### ISSUE TITLE
There is a problem. Could you please help me to solve it?

### ISSUE THREAD

**Issue by DonHz** [regthiery/SeismicWaves#1]
Traceback (most recent call last):
  File "F:\PythonSeismicWaves-master\SeismicWaves.py", line 29, in <module>
    scene = Scene()
            ^^^^^^^
  File "F:\Python\SeismicWaves-master\src\Scene.py", line 61, in __init__
    self.eraseImagesFolder()
  File "F:\Python\SeismicWaves-master\src\Scene.py", line 109, in eraseImagesFolder
    files = os.listdir(self.imagesFolderPath)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system could not find the specified path: 'images'

The process has ended with exit code 1.

**Comment by regthiery** [comment]
Corrected. Thanks

**Comment by DonHz** [comment]
Traceback (most recent call last):
  File "F:\Python\SeismicWaves-master\SeismicWaves.py", line 35, in <module>
    scene.buildFromScript(filename)
  File "F:\Python\SeismicWaves-master\src\Scene.py", line 880, in buildFromScript
    data = self.parseFile(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Python\SeismicWaves-master\src\Scene.py", line 723, in parseFile
    with open ("scripts/"+fileName+".txt", "r") as file:
               ~~~~~~~~~~^~~~~~~~~
TypeError: can only concatenate str (not "NoneType") to str
Process script None


When I run it again, I get the above error. Did you forget to add pictures to the images folder?

**Comment by regthiery** [comment]
It's because you forgot to enter a script name on the command line. The scripts are in the 'scripts' folder. Note that script names are written without the .txt extension on the command line.
For example, type: python3 SeismicWaves.py a00
